"""empty message

Revision ID: 2f9e808646ab
Revises: 1c020b2ae18c
Create Date: 2025-06-29 02:23:28.101821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f9e808646ab'
down_revision = '1c020b2ae18c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('original_content', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('content_hash', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_comments_approved_by'), ['approved_by'], unique=False)
        batch_op.create_foreign_key(None, 'users', ['approved_by'], ['id'])

    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_index('ix_votes_comment_id')
        batch_op.drop_constraint('unique_user_comment_vote', type_='unique')
        batch_op.drop_constraint('votes_comment_id_fkey', type_='foreignkey')
        batch_op.drop_column('comment_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('votes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('votes_comment_id_fkey', 'comments', ['comment_id'], ['id'])
        batch_op.create_unique_constraint('unique_user_comment_vote', ['user_id', 'comment_id'], postgresql_nulls_not_distinct=False)
        batch_op.create_index('ix_votes_comment_id', ['comment_id'], unique=False)
        batch_op.alter_column('post_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_comments_approved_by'))
        batch_op.drop_column('content_hash')
        batch_op.drop_column('original_content')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved_by')

    # ### end Alembic commands ###
