"""Add likes to Comment

Revision ID: 79da9c2804e7
Revises: a516ffcb6c0d
Create Date: 2025-06-20 18:11:28.297694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '79da9c2804e7'
down_revision = 'a516ffcb6c0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likes', sa.Integer(), nullable=False, server_default='0'))



    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_column('likes')

    # ### end Alembic commands ###
