"""Add Like model and update relationships

Revision ID: 81baab3cadbb
Revises: ab1e66514f8a
Create Date: 2025-06-28 02:10:56.950424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81baab3cadbb'
down_revision = 'ab1e66514f8a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment_likes')
    op.drop_table('post_likes')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post_likes',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('post_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['posts.id'], name='post_likes_post_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='post_likes_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'post_id', name='post_likes_pkey')
    )
    op.create_table('comment_likes',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('comment_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], name='comment_likes_comment_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='comment_likes_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', 'comment_id', name='comment_likes_pkey')
    )
    # ### end Alembic commands ###
