"""Add is_flagged and is_approved to posts

Revision ID: a516ffcb6c0d
Revises: d376393fa4f5
Create Date: 2025-06-20 15:23:35.382913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a516ffcb6c0d'
down_revision = 'd376393fa4f5'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('posts') as batch_op:
        batch_op.add_column(sa.Column('is_flagged', sa.Boolean(), nullable=False, server_default=sa.text('0')))
        batch_op.add_column(sa.Column('is_approved', sa.Boolean(), nullable=False, server_default=sa.text('1')))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_column('is_approved')
        batch_op.drop_column('is_flagged')

    # ### end Alembic commands ###
